### PR TITLE
feat: support setting custom dns-service-ip via --dns-service-ip flag

### PR DESCRIPTION
**Pull request by Bryce-Soghigian**
Fixes # 

**Description**

**How was this change tested?**

*

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [ ] No

**Release Note**

```release-note

```

### CODE REVIEW

**Comment by Bryce-Soghigian** [comment]
Closing this will reopen in a couple of weeks after I finish the azure cni work

**Comment by demeesterdev** [comment]
@Bryce-Soghigian have you had any chance working on this since may?

**Comment by Bryce-Soghigian** [comment]
cc: @comtalyst

**Comment by tangyouzzz** [comment]
The pod on the node I created using Karpenter cannot be resolved correctly using kube dns. It seems that we still need to add `args["--cluster-dns"] = strings.Join(kubeletConfig.ClusterDNS, ",")` to bootstrap. Can I complete it?

**Comment by Bryce-Soghigian** [comment]
We are no longer taking this approach and will be solving it differently in this pr https://github.com/Azure/karpenter-provider-azure/pull/527

**Comment by comtalyst** [comment]
FYI #527 will be enabled for Node Auto Provisioning (managed offering) only for now.

**Comment by Bryce-Soghigian** [comment]
@tangyouzzz  if you want to do a pr to make it work for self hosted feel free and I will review it.

**Comment by ppodevlabs** [comment]
Any chance this get enabled also on self hosted?

**Pull request closed without merging**
