### PR TITLE
test(e2e): add in debug package for e2e testing

### PR DESCRIPTION
**Pull request by charliedmcb**
Fixes # 

**Description**
I went through the `debug` package and vetted it. Everything seems good, safe, and useful from what I saw.

So, wanting to add this additional info to our E2E testing for debugging.

From the debugging package we get:
- Throughout the updates on `Node`, `NodeClaim`, and `Pod` info as they changes
- Event dump for `Node`, `NodeClaim`, and `Pod` that happened during the test (dump at the end)

**How was this change tested?**
Vetted the entire `debug` package, and everything looks fine.

I'll also be running the regular e2e pipeline before checking in.
*

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [x] No

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Review by charliedmcb — COMMENTED** [review]
/test

**Review by charliedmcb — COMMENTED** [review]
/test

**Review by charliedmcb — COMMENTED** [review]
/test

**Review by charliedmcb — COMMENTED** [review]
/test

**Review by tallaxes — APPROVED** [review]
LGTM. (Would be good to have an overview/summary of what debug gets us.)

**Review by charliedmcb — COMMENTED** [review]
/test

**Comment by charliedmcb** [comment]
> LGTM. (Would be good to have an overview/summary of what debug gets us.)

Added a minor description to this PR, but curious if we might want to start using the wiki on this repo, or something similar to collect info like this for the repo specificly.

**Pull request merged**
