### PR TITLE
chore: remove ClusterID from user input

### LINKED ISSUE #130: ClusterID may not be needed as an input
### Tell us about your request

`ClusterID` is currently an optional input from the user. If not provided, a randomized ID will be generated based on `ClusterEndpoint`. However, it may not be useful for user to provide it.
Had an additional discussion offline.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

Evaluate the idea of removing the ability to provide `ClusterID` from the interface.

### Are you currently working around this issue?

Yes

### Additional Context

_No response_

### Attachments

_No response_

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by krkeshav**
Fixes #130

**Description**

**How was this change tested?**

* Tested by running UT tests

**Does this change impact docs?**
- [x] Yes, PR includes docs updates
- [x] Yes, issue opened: # 130
- [ ] No

**Release Note**

```release-note
Stopped reading ClusterID as an input from env variable and modified the tests accordingly.

```

### CODE REVIEW

**Comment by krkeshav** [comment]
> @krkeshav please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Review by Bryce-Soghigian — COMMENTED** [review]
/test

**Review by Bryce-Soghigian — APPROVED** [review]
Testing locally looks like it behaves as we would expect. Still seeing some flake on utilization. If it passes we are good to merge.

**Review by Bryce-Soghigian — APPROVED** [review]
/test

**Pull request merged**
