### PR TITLE
test(e2e): add expected startupTaints for e2e testing

### PR DESCRIPTION
**Pull request by charliedmcb**
Fixes # 

**Description**

**How was this change tested?**

*

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [ ] No

**Release Note**

```release-note

```

### CODE REVIEW

**Review by charliedmcb — COMMENTED** [review]
/test

**Review by charliedmcb — COMMENTED** [review]
/test

**Review by charliedmcb — COMMENTED** [review]
/test

**Review by charliedmcb — COMMENTED** [review]
/test

**Review by Bryce-Soghigian — COMMENTED** [review]
/test

**Review by Bryce-Soghigian — COMMENTED** [review]
/test

**Review by Bryce-Soghigian — COMMENTED** [review]
/test

**Review by Bryce-Soghigian — COMMENTED** [review]
/test

**Review by Bryce-Soghigian — COMMENTED** [review]
/test

**Review by Bryce-Soghigian — COMMENTED** [review]
/test

**Review by Bryce-Soghigian — COMMENTED** [review]
/test

**Review by Bryce-Soghigian — COMMENTED** [review]
/test

**Review by Bryce-Soghigian — COMMENTED** [review]
/test

**Review by Bryce-Soghigian — COMMENTED** [review]
/test

**Review by Bryce-Soghigian — COMMENTED** [review]
/test

**Comment by Bryce-Soghigian** [comment]
We should also launch 10 tests without taints and see waht fails, here we only see one failure case for utilization, and its due to underprovisioning

**Review by charliedmcb — COMMENTED** [review]
/test

**Pull request closed without merging**
