### PR TITLE
fix typos using https://crates.io/crates/typos-cli

### PR DESCRIPTION
**Pull request by Takashiidobe**
Fixes # 

**Description**

This PR uses https://crates.io/crates/typos-cli in order to fix some typos in docs and go code. The config file I used was:

```toml
[default.extend-words]
# karpenter-provider-azure
als = "als"
ERRO = "ERRO"
```

If you'd like to use it in the future.

There was one extra typo that I found, but I believe it's an imported module, so the typo would need to be fixed there for it to apply:

```diff
diff --git a/pkg/apis/v1alpha2/labels.go b/pkg/apis/v1alpha2/labels.go
index 6b55f4b..2aee2ce 100644
--- a/pkg/apis/v1alpha2/labels.go
+++ b/pkg/apis/v1alpha2/labels.go
@@ -68,7 +68,7 @@ var (
 		LabelSKUHyperVGeneration,
 	)
 
-	AllowUndefinedLabels = func(options scheduling.CompatabilityOptions) scheduling.CompatabilityOptions {
+	AllowUndefinedLabels = func(options scheduling.CompatibilityOptions) scheduling.CompatibilityOptions {
 		options.AllowUndefined = corev1beta1.WellKnownLabels.Union(RestrictedLabels)
 		return options
 	}
```

As such, I have excluded it from this PR.

**How was this change tested?**

* It wasn't tested. 

**Does this change impact docs?**
- [x] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [ ] No

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Comment by Takashiidobe** [comment]
@microsoft-github-policy-service agree

**Comment by Bryce-Soghigian** [comment]
@Takashiidobe  thanks for contributing, if we are going down this path it might make sense to add some sort of spellcheck linter to properly check these types of things.

**Comment by Takashiidobe** [comment]
Sure, this crate also provides instructions on how to set up a github action to check spelling in ci: https://github.com/crate-ci/typos/blob/master/docs/github-action.md

It could be set up to run on PRs with the config file i provided, but if a new word is added that the cli doesn't understand then it will block the pr unless that word is added as an exception in the typos config file, which can be cumbersome. If you'd like to use it as a diagnostic, It could be added as a non blocking ci job too.

**Review by tallaxes — APPROVED** [review]

**Comment by tallaxes** [comment]
Or pre-commmit? https://github.com/Azure/karpenter-provider-azure/pull/113

**Pull request merged**
