### PR TITLE
[Pre-PR]add h100 on gpu sku

### LINKED ISSUE #517: H100 support
### Tell us about your request

H100 VM can't be used for node pool. Registered UAT of MSFT internal as well 

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

H100 is definitely supported by Karpenter. 

### Are you currently working around this issue?

No workaround for now

### Additional Context

_No response_

### Attachments

_No response_

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by HakjunMIN**
Fixes #517 

**Description**

Make Karpenter provision H100 node

**How was this change tested?**

Not yet. This pre-PR is for @Bryce-Soghigian to validate code itself prior to apply the cluster where h100 is available at.
*

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [X] Yes, issue opened: #517 
- [ ] No

**Release Note**

```release-note

```

### CODE REVIEW

**Comment by HakjunMIN** [comment]
Not sure `zz_generated.pricing.go` is valid which is just generated by `codegen.sh` in local.

**Comment by Bryce-Soghigian** [comment]
Did you validate it with an h100? Can you show some screenshots of it joining the cluster?

**Comment by HakjunMIN** [comment]
@Bryce-Soghigian Of course NOT. This is **Pre-PR**. I'm not sure the code that I changed is enough so I'm asking you to review 
it roughly. Then I'll start to test with this in customer environment that owns H100.

Please check code itself first.

**Comment by Bryce-Soghigian** [comment]
Yes it looks right, that list is used to determine which skus we allow as gpu skus, so this should do the trick.

**Comment by HakjunMIN** [comment]
@Bryce-Soghigian Got it. I should share the result with you after testing on H100. 

I'll use `Build and publish to MCR` pipeline in order to packaging and my ACR. 
Is there any caution or something to move forward?

**Comment by Bryce-Soghigian** [comment]
You can't use those stages, you shuld use the make commands to test it locally. 

Use make az-all

**Comment by HakjunMIN** [comment]
Okay. Thank you!

**Comment by HakjunMIN** [comment]
@Bryce-Soghigian Hey, during validation on the cluseter an error is happening like https://github.com/Azure/karpenter-provider-azure/issues/579. I',m just suspecting the image version of Ubunt image because similar error is happened in other Korea company. However found https://github.com/Azure/karpenter-provider-azure/pull/531 which image version was deleted in nodeclass.

Could you look through this bug?

**Comment by tallaxes** [comment]
@HakjunMIN, appreciate you bringing this to our attention and contributing the fix! Expect this to be superseded by #587, which refreshes the list of GPUs supported (and fixes GPU bootstrap)

**Pull request closed without merging**
