### PR TITLE
chore: removing webhooks from existence for the AKS provider

### PR DESCRIPTION
**Pull request by Bryce-Soghigian**
Fixes # 

**Description**
Removing the webhooks from our self hosted provider. 

**How was this change tested?**

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [ ] No

**Release Note**

```release-note

```

### CODE REVIEW

**Review by Bryce-Soghigian — COMMENTED** [review]
/test

**Review by Bryce-Soghigian — COMMENTED** [review]
/test

**Review by comtalyst — DISMISSED** [review]
lgtm

**Review by comtalyst — APPROVED** [review]
approved

**Pull request merged**
